### ISSUE TITLE
 Cannot find module 'botkit'

### ISSUE THREAD

**Issue by vphimmasone** [BroadSoft-Xtended/SampleApps#4]
Hi,
Can someone help on that issue : 
i ran the demo_bot.js on my local server and this is the error i have 

$token=XXXXXXXXXXXXXXXXXXXXXX node demo_bot.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'botkit'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/src/test/SampleApps/team-one/botkit/botkit/examples/demo_bot.js:90:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10

Pretty newbie on this :) . 

Thanks
Vanna

**Comment by joncodo** [comment]
try `npm install --save botkit`

**Comment by vphimmasone** [comment]
I did :) while looking at botkit 
# /usr/local/bin/npm install --save botkit
npm WARN engine request@2.81.0: wanted: {"node":">= 4"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN engine form-data@2.1.4: wanted: {"node":">= 0.12"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine har-validator@4.2.1: wanted: {"node":">=4"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine jsonwebtoken@5.4.1: wanted: {"npm":">=1.4.28"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine find-replace@1.0.3: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine array-back@1.0.4: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine har-schema@1.0.5: wanted: {"node":">=4"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine jsonwebtoken@7.4.2: wanted: {"npm":">=1.4.28","node":">=0.12"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine joi@6.10.1: wanted: {"node":">=0.10.40","npm":">=2.0.0"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.30","npm":"1.4.21"})
npm WARN engine topo@1.1.0: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.30","npm":"1.4.21"})
botkit@0.4.10 node_modules/botkit
├── botkit-studio-sdk@1.0.2
├── clone@2.0.0
├── crypto@0.0.3
├── md5@2.2.1 (charenc@0.0.2, crypt@0.0.2, is-buffer@1.1.5)
├── randomstring@1.1.5 (array-uniq@1.0.2)
├── back@1.0.1 (xtend@4.0.1)
├── mustache@2.3.0
├── ware@1.3.0 (wrap-fn@0.1.5)
├── https-proxy-agent@1.0.0 (extend@3.0.1, debug@2.6.8, agent-base@2.1.1)
├── promise@7.3.1 (asap@2.0.6)
├── body-parser@1.17.2 (bytes@2.4.0, content-type@1.0.2, depd@1.1.1, on-finished@2.3.0, raw-body@2.2.0, http-errors@1.6.2, debug@2.6.7, qs@6.4.0, type-is@1.6.15, iconv-lite@0.4.15)
├── localtunnel@1.8.3 (openurl@1.1.1, debug@2.6.8, yargs@3.29.0)
├── command-line-args@3.0.5 (array-back@1.0.4, typical@2.6.1, feature-detect-es6@1.3.1, find-replace@1.0.3)
├── jfs@0.2.6 (clone@1.0.2, node-uuid@1.4.8, mkdirp@0.5.1, async@1.2.1)
├── express@4.15.4 (setprototypeof@1.0.3, escape-html@1.0.3, array-flatten@1.1.1, utils-merge@1.0.0, cookie-signature@1.0.6, merge-descriptors@1.0.1, methods@1.1.2, path-to-regexp@0.1.7, encodeurl@1.0.1, range-parser@1.2.0, parseurl@1.3.1, fresh@0.5.0, vary@1.1.1, content-type@1.0.2, etag@1.8.0, statuses@1.3.1, cookie@0.3.1, content-disposition@0.5.2, serve-static@1.12.4, depd@1.1.1, on-finished@2.3.0, finalhandler@1.0.4, qs@6.5.0, proxy-addr@1.1.5, send@0.15.4, debug@2.6.8, type-is@1.6.15, accepts@1.3.3)
├── twilio@2.11.1 (string.prototype.startswith@0.2.0, deprecate@0.1.0, scmp@0.0.3, q@0.9.7, underscore@1.8.3, jsonwebtoken@5.4.1, request@2.74.0)
├── request@2.81.0 (is-typedarray@1.0.0, oauth-sign@0.8.2, aws-sign2@0.6.0, forever-agent@0.6.1, tunnel-agent@0.6.0, stringstream@0.0.5, caseless@0.12.0, isstream@0.1.2, json-stringify-safe@5.0.1, safe-buffer@5.1.1, performance-now@0.2.0, extend@3.0.1, aws4@1.6.0, uuid@3.1.0, combined-stream@1.0.5, form-data@2.1.4, qs@6.4.0, tough-cookie@2.3.2, mime-types@2.1.16, http-signature@1.1.1, hawk@3.1.3, har-validator@4.2.1)
├── async@2.5.0 (lodash@4.17.4)
└── botbuilder@3.9.0 (url-join@1.1.0, rsa-pem-from-mod-exp@0.8.4, sprintf-js@1.1.1, base64url@2.0.0, async@1.5.2, chrono-node@1.3.5, jsonwebtoken@7.4.2)


Then run again and i have another error message :)

token=XXXXXXXXXXXX node demo_bot.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'botkit-teamone'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/src/test/SampleApps/team-one/botkit/examples/demo_bot.js:91:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

Almost there 

Thanks for your response by the way i appreciate that

**Comment by joncodo** [comment]
`npm i botkit-teamone`?

**Comment by vphimmasone** [comment]
Well we are almost there 👍 
token=XXXXXXXXX node demo_bot.js

/usr/src/test/SampleApps/team-one/botkit/examples/demo_bot.js:97
var controller = Botkit.teamonebot({ debug: false });
                        ^
TypeError: Object #<Object> has no method 'teamonebot'
    at Object.<anonymous> (/usr/src/test/SampleApps/team-one/botkit/examples/demo_bot.js:97:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

What do you think ?

**Comment by vphimmasone** [comment]
Do you know where i can find the teamonebot controller ?

**Comment by vphimmasone** [comment]
K found my issue
